openapi: "3.0.0"
info:
  title: cloth store api
  description: online store
  version: 1.1.0
  contact:
    email: dhyanpatel7054@gmail.com
    url: "https://lco.dev"
servers:
- url: "{protocol}://localhost:4000/api/{version}"
  description: for local host
  variables:
    version:
      enum:
      - v1
      - v2
      default: v1
    protocol:
      enum:
      - http
      - https
      default: http
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /lco:
    get:
      tags:
      - string
      summary: returns a greet message fro LOC
      responses:
        200:
          description: all good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: bad request
        500:
          description: internal server error
